const express=require('express');
const http=require('http');
const path=require('path');
const fs=require('fs');
const crypto=require('crypto');
const Database=require('better-sqlite3');
const multer=require('multer');
const nodemailer=require('nodemailer');
const {WebSocketServer}=require('ws');
const bcrypt=require('bcryptjs');
try{require('dotenv').config()}catch{}

const PORT=Number(process.env.PORT||3000), ROOT=__dirname;
const PUBLIC=path.join(ROOT,'public'), UPLOADS=path.join(ROOT,'uploads'), DATA=path.join(ROOT,'data');
fs.mkdirSync(UPLOADS,{recursive:true}); fs.mkdirSync(DATA,{recursive:true});
const DB_FILE=path.join(DATA,'vybinka.sqlite');
const db=new Database(DB_FILE);
db.pragma('journal_mode = WAL');
function hasColumn(table,column){return db.prepare(`PRAGMA table_info(${table})`).all().some(c=>c.name===column)}
function addColumn(table,column,type,def=''){if(!hasColumn(table,column))db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${type}${def?` DEFAULT ${def}`:''}`)}
db.exec(`
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password_hash TEXT NOT NULL,age INTEGER NOT NULL,gender TEXT NOT NULL,city TEXT,bio TEXT,interests TEXT,looking_for TEXT,avatar TEXT,cover TEXT,music TEXT,mood TEXT,mood_date TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS likes(user_id TEXT NOT NULL,target_id TEXT NOT NULL,action TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(user_id,target_id));
CREATE TABLE IF NOT EXISTS blocks(user_id TEXT NOT NULL,target_id TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(user_id,target_id));
CREATE TABLE IF NOT EXISTS chats(id TEXT PRIMARY KEY,type TEXT NOT NULL,name TEXT,owner_id TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chat_members(chat_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT DEFAULT 'member',banned INTEGER DEFAULT 0,PRIMARY KEY(chat_id,user_id));
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,chat_id TEXT NOT NULL,sender_id TEXT NOT NULL,type TEXT NOT NULL,content TEXT,reply_to TEXT,forwarded_from TEXT,one_view INTEGER DEFAULT 0,viewed INTEGER DEFAULT 0,edited INTEGER DEFAULT 0,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reactions(message_id TEXT NOT NULL,user_id TEXT NOT NULL,emoji TEXT NOT NULL,PRIMARY KEY(message_id,user_id));
CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,reporter_id TEXT NOT NULL,target_id TEXT,chat_id TEXT,reason TEXT,created_at TEXT NOT NULL,status TEXT DEFAULT 'open');
CREATE TABLE IF NOT EXISTS channels(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,name TEXT NOT NULL,description TEXT,owner_id TEXT NOT NULL,avatar TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS channel_members(channel_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT DEFAULT 'subscriber',PRIMARY KEY(channel_id,user_id));
CREATE TABLE IF NOT EXISTS channel_posts(id TEXT PRIMARY KEY,channel_id TEXT NOT NULL,author_id TEXT NOT NULL,content TEXT,media TEXT,created_at TEXT NOT NULL);
`);
// Lightweight migrations for databases created by earlier VYBINKA builds.
for (const [c,t,d] of [['cover','TEXT',''],['music','TEXT',''],['mood','TEXT',"''"],['mood_date','TEXT',"''"]]) addColumn('users',c,t,d);
for (const [c,t,d] of [['reply_to','TEXT','NULL'],['forwarded_from','TEXT','NULL'],['one_view','INTEGER','0'],['viewed','INTEGER','0'],['edited','INTEGER','0']]) addColumn('messages',c,t,d);


const now=()=>new Date().toISOString();
const id=()=>crypto.randomUUID();
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function json(res,status,data){res.status(status).json(data)}
function parseJSON(v,f=[]){try{return v?JSON.parse(v):f}catch{return f}}
function publicUser(u){return {id:u.id,username:u.username,name:u.name,age:u.age,gender:u.gender,city:u.city,bio:u.bio,interests:parseJSON(u.interests),lookingFor:parseJSON(u.looking_for),avatar:u.avatar,cover:u.cover,music:u.music,mood:u.mood,moodDate:u.mood_date}};
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return json(res,401,{error:'auth_required'});const token=h.slice(7),s=db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(hash(token));if(!s||s.expires_at<Date.now())return json(res,401,{error:'session_expired'});const u=db.prepare('SELECT * FROM users WHERE id=?').get(s.user_id);if(!u)return json(res,401,{error:'user_missing'});req.user=u;next()}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>2e6)req.destroy()});req.on('end',()=>{try{resolve(JSON.parse(raw||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
const app=express();app.use(express.json({limit:'2mb'}));app.use('/uploads',express.static(UPLOADS));app.use(express.static(PUBLIC));
const upload=multer({dest:UPLOADS,limits:{fileSize:50*1024*1024},fileFilter:(req,file,cb)=>{if(/^image\//.test(file.mimetype)||/^video\//.test(file.mimetype)||/^audio\//.test(file.mimetype))cb(null,true);else cb(new Error('unsupported_file'))}});

app.get('/api/health',(req,res)=>json(res,200,{ok:true,version:'1.0.0',mistralConfigured:!!process.env.MISTRAL_API_KEY,smtpConfigured:!!process.env.SMTP_HOST}));
app.post('/api/auth/register',async(req,res)=>{
  try{
    const b=req.body||{};
    const age=Number(b.age);
    const name=String(b.name||'').trim().slice(0,80);
    let username=String(b.username||'').trim();
    const password=String(b.password||'');
    if(!name)return json(res,400,{error:'name_required'});
    if(!username.startsWith('@')) username='@'+username;
    if(!/^@[A-Za-z0-9_]{3,20}$/.test(username))return json(res,400,{error:'bad_username'});
    if(!Number.isInteger(age)||age<10||age>120)return json(res,400,{error:'bad_age'});
    if(password.length<8)return json(res,400,{error:'password_short'});
    const lookingFor=Array.isArray(b.lookingFor)?b.lookingFor:[];
    if(age<18&&lookingFor.includes('Отношения (18+)'))return json(res,400,{error:'minor_relationship_blocked'});
    if(db.prepare('SELECT 1 FROM users WHERE lower(username)=lower(?)').get(username))return json(res,409,{error:'username_taken'});
    const uid=id(),ph=await bcrypt.hash(password,12);
    const user={uid,username,name,ph,age,gender:String(b.gender||'other'),city:String(b.city||'').slice(0,120),bio:String(b.bio||'').slice(0,2000),interests:JSON.stringify(Array.isArray(b.interests)?b.interests.slice(0,50):[]),lookingFor:JSON.stringify(lookingFor.length?lookingFor:['Дружба']),avatar:String(b.avatar||''),cover:String(b.cover||''),music:String(b.music||'')};
    const tx=db.transaction(()=>{
      db.prepare('INSERT INTO users(id,username,name,password_hash,age,gender,city,bio,interests,looking_for,avatar,cover,music,mood,mood_date,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(user.uid,user.username,user.name,user.ph,user.age,user.gender,user.city,user.bio,user.interests,user.lookingFor,user.avatar,user.cover,user.music,'','',now());
      const token=crypto.randomBytes(32).toString('hex');
      db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').run(hash(token),uid,Date.now()+Number(process.env.SESSION_DAYS||30)*86400000);
      return token;
    });
    const token=tx();
    return json(res,201,{token,user:publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(uid)),onboardingRequired:true});
  }catch(e){
    console.error('REGISTER:',e.stack||e);
    if(String(e.code||'').includes('SQLITE_CONSTRAINT'))return json(res,409,{error:'username_taken'});
    return json(res,500,{error:'registration_failed',detail:process.env.NODE_ENV==='development'?String(e.message):undefined});
  }
});
app.post('/api/auth/login',async(req,res)=>{const b=req.body||{},u=db.prepare('SELECT * FROM users WHERE lower(username)=lower(?)').get(String(b.username||''));if(!u||!(await bcrypt.compare(String(b.password||''),u.password_hash)))return json(res,401,{error:'invalid_credentials'});const token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),u.id,Date.now()+Number(process.env.SESSION_DAYS||30)*86400000);json(res,200,{token,user:publicUser(u)})});
app.post('/api/auth/logout',auth,(req,res)=>{db.prepare('DELETE FROM sessions WHERE user_id=?').run(req.user.id);json(res,200,{ok:true})});
app.get('/api/me',auth,(req,res)=>json(res,200,{user:publicUser(req.user)}));
app.put('/api/me',auth,(req,res)=>{const b=req.body||{};const age=Number(b.age||req.user.age);if(age<10)return json(res,400,{error:'age'});db.prepare('UPDATE users SET name=?,age=?,gender=?,city=?,bio=?,interests=?,looking_for=?,avatar=?,cover=?,music=?,mood=?,mood_date=? WHERE id=?').run(b.name||req.user.name,age,b.gender||req.user.gender,b.city??req.user.city,b.bio??req.user.bio,JSON.stringify(b.interests||parseJSON(req.user.interests)),JSON.stringify(b.lookingFor||parseJSON(req.user.looking_for)),b.avatar??req.user.avatar,b.cover??req.user.cover,b.music??req.user.music,b.mood??req.user.mood,b.moodDate??req.user.mood_date,req.user.id);json(res,200,{user:publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id))})});
app.post('/api/me/mood',auth,(req,res)=>{const mood=String(req.body.mood||'').slice(0,40);db.prepare('UPDATE users SET mood=?,mood_date=? WHERE id=?').run(mood,new Date().toISOString().slice(0,10),req.user.id);json(res,200,{ok:true})});
app.post('/api/upload',auth,upload.single('file'),(req,res)=>{if(!req.file)return json(res,400,{error:'file_missing'});const ext=path.extname(req.file.originalname).replace(/[^a-z0-9.]/gi,'').slice(0,8)||'';const dest=path.join(UPLOADS,req.file.filename+ext);fs.renameSync(req.file.path,dest);json(res,201,{url:'/uploads/'+path.basename(dest),type:req.file.mimetype,size:req.file.size})});

app.get('/api/users',auth,(req,res)=>{const q=String(req.query.search||'').trim().toLowerCase();const limit=Math.min(50,Math.max(1,Number(req.query.limit||20)));let rows;if(q)rows=db.prepare(`SELECT * FROM users WHERE id<>? AND lower(username) LIKE ? LIMIT ?`).all(req.user.id,q+'%',limit);else rows=db.prepare('SELECT * FROM users WHERE id<>? ORDER BY created_at DESC LIMIT ?').all(req.user.id,limit);const blocked=db.prepare('SELECT target_id FROM blocks WHERE user_id=?').all(req.user.id).map(x=>x.target_id);json(res,200,{users:rows.filter(x=>!blocked.includes(x.id)).map(publicUser)})});
app.get('/api/users/:username',auth,(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE lower(username)=lower(?)').get(req.params.username.startsWith('@')?req.params.username:'@'+req.params.username);if(!u)return json(res,404,{error:'not_found'});json(res,200,{user:publicUser(u)})});
app.post('/api/users/:id/action',auth,(req,res)=>{const target=db.prepare('SELECT * FROM users WHERE id=?').get(req.params.id);if(!target||target.id===req.user.id)return json(res,404,{error:'not_found'});const action=req.body.action==='like'?'like':'pass';db.prepare('INSERT INTO likes VALUES(?,?,?,?) ON CONFLICT(user_id,target_id) DO UPDATE SET action=excluded.action,created_at=excluded.created_at').run(req.user.id,target.id,action,now());let match=false;if(action==='like'){const back=db.prepare(`SELECT 1 FROM likes WHERE user_id=? AND target_id=? AND action='like'`).get(target.id,req.user.id);match=!!back}json(res,200,{ok:true,match})});
app.get('/api/likes',auth,(req,res)=>{const incoming=db.prepare(`SELECT u.* FROM likes l JOIN users u ON u.id=l.user_id WHERE l.target_id=? AND l.action='like'`).all(req.user.id).map(publicUser);const outgoing=db.prepare(`SELECT u.* FROM likes l JOIN users u ON u.id=l.target_id WHERE l.user_id=? AND l.action='like'`).all(req.user.id).map(publicUser);json(res,200,{incoming,outgoing})});
app.post('/api/blocks/:id',auth,(req,res)=>{db.prepare('INSERT OR IGNORE INTO blocks VALUES(?,?,?)').run(req.user.id,req.params.id,now());json(res,200,{ok:true})});
app.delete('/api/blocks/:id',auth,(req,res)=>{db.prepare('DELETE FROM blocks WHERE user_id=? AND target_id=?').run(req.user.id,req.params.id);json(res,200,{ok:true})});

function userChats(uid){return db.prepare(`SELECT c.*,cm.role FROM chats c JOIN chat_members cm ON cm.chat_id=c.id WHERE cm.user_id=? AND cm.banned=0 ORDER BY c.created_at DESC`).all(uid)}
app.get('/api/chats',auth,(req,res)=>{const cs=userChats(req.user.id).map(c=>{const members=db.prepare(`SELECT u.id,u.username,u.name,u.avatar,cm.role FROM chat_members cm JOIN users u ON u.id=cm.user_id WHERE cm.chat_id=? AND cm.banned=0`).all(c.id);const messages=db.prepare(`SELECT * FROM messages WHERE chat_id=? ORDER BY created_at ASC LIMIT 200`).all(c.id).map(m=>({...m,reactions:db.prepare('SELECT emoji,user_id FROM reactions WHERE message_id=?').all(m.id)}));return {...c,members,messages}});json(res,200,{chats:cs})});
app.post('/api/chats/direct/:userId',auth,(req,res)=>{const other=db.prepare('SELECT * FROM users WHERE id=?').get(req.params.userId);if(!other)return json(res,404,{error:'user_missing'});if(db.prepare('SELECT 1 FROM blocks WHERE user_id=? AND target_id=?').get(req.user.id,other.id)||db.prepare('SELECT 1 FROM blocks WHERE user_id=? AND target_id=?').get(other.id,req.user.id))return json(res,403,{error:'blocked'});const existing=db.prepare(`SELECT c.id FROM chats c JOIN chat_members a ON a.chat_id=c.id JOIN chat_members b ON b.chat_id=c.id WHERE c.type='direct' AND a.user_id=? AND b.user_id=?`).get(req.user.id,other.id);if(existing)return json(res,200,{chatId:existing.id});const cid=id();const tx=db.transaction(()=>{db.prepare('INSERT INTO chats VALUES(?,?,?,?,?)').run(cid,'direct',null,null,now());db.prepare('INSERT INTO chat_members VALUES(?,?,?,0)').run(cid,req.user.id,'member');db.prepare('INSERT INTO chat_members VALUES(?,?,?,0)').run(cid,other.id,'member')});tx();json(res,201,{chatId:cid})});
app.delete('/api/chats/:id',auth,(req,res)=>{const m=db.prepare('SELECT 1 FROM chat_members WHERE chat_id=? AND user_id=?').get(req.params.id,req.user.id);if(!m)return json(res,404,{error:'not_found'});const tx=db.transaction(()=>{db.prepare('DELETE FROM reactions WHERE message_id IN (SELECT id FROM messages WHERE chat_id=?)').run(req.params.id);db.prepare('DELETE FROM messages WHERE chat_id=?').run(req.params.id);db.prepare('DELETE FROM chat_members WHERE chat_id=?').run(req.params.id);db.prepare('DELETE FROM chats WHERE id=?').run(req.params.id)});tx();json(res,200,{ok:true})});
app.post('/api/chats/:id/block',auth,(req,res)=>{const other=db.prepare('SELECT user_id FROM chat_members WHERE chat_id=? AND user_id<>? LIMIT 1').get(req.params.id,req.user.id);if(other)db.prepare('INSERT OR IGNORE INTO blocks VALUES(?,?,?)').run(req.user.id,other.user_id,now());json(res,200,{ok:true})});
app.post('/api/chats/:id/messages',auth,async(req,res)=>{const m=db.prepare('SELECT 1 FROM chat_members WHERE chat_id=? AND user_id=? AND banned=0').get(req.params.id,req.user.id);if(!m)return json(res,403,{error:'not_member'});const b=req.body||{},msgId=id(),type=['text','sticker','photo','video','voice'].includes(b.type)?b.type:'text';db.prepare('INSERT INTO messages VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(msgId,req.params.id,req.user.id,type,String(b.content||''),b.replyTo||null,b.forwardedFrom||null,b.oneView?1:0,0,0,now());const msg=db.prepare('SELECT * FROM messages WHERE id=?').get(msgId);broadcast(req.params.id,{event:'message',message:msg});json(res,201,{message:msg})});
app.patch('/api/messages/:id',auth,(req,res)=>{const m=db.prepare('SELECT * FROM messages WHERE id=? AND sender_id=?').get(req.params.id,req.user.id);if(!m)return json(res,404,{error:'not_found'});db.prepare('UPDATE messages SET content=?,edited=1 WHERE id=?').run(String(req.body.content||''),m.id);const x=db.prepare('SELECT * FROM messages WHERE id=?').get(m.id);broadcast(m.chat_id,{event:'message_updated',message:x});json(res,200,{message:x})});
app.delete('/api/messages/:id',auth,(req,res)=>{const m=db.prepare('SELECT * FROM messages WHERE id=? AND sender_id=?').get(req.params.id,req.user.id);if(!m)return json(res,404,{error:'not_found'});db.prepare('DELETE FROM reactions WHERE message_id=?').run(m.id);db.prepare('DELETE FROM messages WHERE id=?').run(m.id);broadcast(m.chat_id,{event:'message_deleted',id:m.id});json(res,200,{ok:true})});
app.post('/api/messages/:id/view',auth,(req,res)=>{const m=db.prepare('SELECT * FROM messages WHERE id=?').get(req.params.id);if(!m)return json(res,404,{error:'not_found'});if(m.one_view&&m.sender_id!==req.user.id&&!m.viewed){db.prepare('UPDATE messages SET viewed=1 WHERE id=?').run(m.id);setTimeout(()=>db.prepare('DELETE FROM messages WHERE id=?').run(m.id),1200);broadcast(m.chat_id,{event:'message_deleted',id:m.id});}json(res,200,{ok:true})});
app.post('/api/messages/:id/reaction',auth,(req,res)=>{const m=db.prepare('SELECT * FROM messages WHERE id=?').get(req.params.id);if(!m)return json(res,404,{error:'not_found'});if(!db.prepare('SELECT 1 FROM chat_members WHERE chat_id=? AND user_id=? AND banned=0').get(m.chat_id,req.user.id))return json(res,403,{error:'not_member'});const e=String(req.body.emoji||'❤️').slice(0,8);db.prepare('INSERT INTO reactions VALUES(?,?,?) ON CONFLICT(message_id,user_id) DO UPDATE SET emoji=excluded.emoji').run(m.id,req.user.id,e);broadcast(m.chat_id,{event:'reaction',messageId:m.id,emoji:e,userId:req.user.id});json(res,200,{ok:true})});
app.post('/api/messages/:id/forward',auth,(req,res)=>{const m=db.prepare('SELECT * FROM messages WHERE id=?').get(req.params.id);const dest=String(req.body.chatId||'');if(!m||!db.prepare('SELECT 1 FROM chat_members WHERE chat_id=? AND user_id=? AND banned=0').get(m.chat_id,req.user.id)||!db.prepare('SELECT 1 FROM chat_members WHERE chat_id=? AND user_id=? AND banned=0').get(dest,req.user.id))return json(res,404,{error:'not_found'});const mid=id();db.prepare('INSERT INTO messages VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(mid,dest,req.user.id,m.type,m.content,m.reply_to,m.id,0,0,0,now());const x=db.prepare('SELECT * FROM messages WHERE id=?').get(mid);broadcast(dest,{event:'message',message:x});json(res,201,{message:x})});

app.post('/api/groups',auth,(req,res)=>{const cid=id();const tx=db.transaction(()=>{db.prepare('INSERT INTO chats VALUES(?,?,?,?,?)').run(cid,'group',String(req.body.name||'Новая группа').slice(0,80),req.user.id,now());db.prepare('INSERT INTO chat_members VALUES(?,?,?,0)').run(cid,req.user.id,'owner')});tx();json(res,201,{chatId:cid})});
app.post('/api/groups/:id/members',auth,(req,res)=>{const g=db.prepare('SELECT * FROM chats WHERE id=? AND type=\'group\'').get(req.params.id);const owner=db.prepare('SELECT 1 FROM chat_members WHERE chat_id=? AND user_id=? AND role IN (\'owner\',\'admin\')').get(req.params.id,req.user.id);if(!g||!owner)return json(res,403,{error:'forbidden'});db.prepare('INSERT OR IGNORE INTO chat_members VALUES(?,?,?,0)').run(g.id,req.body.userId,'member');json(res,200,{ok:true})});
app.post('/api/groups/:id/ban',auth,(req,res)=>{const owner=db.prepare('SELECT 1 FROM chat_members WHERE chat_id=? AND user_id=? AND role IN (\'owner\',\'admin\')').get(req.params.id,req.user.id);if(!owner)return json(res,403,{error:'forbidden'});db.prepare('UPDATE chat_members SET banned=1 WHERE chat_id=? AND user_id=?').run(req.params.id,req.body.userId);json(res,200,{ok:true})});
app.get('/api/groups/:id',auth,(req,res)=>{const g=db.prepare(`SELECT * FROM chats WHERE id=? AND type='group'`).get(req.params.id);if(!g)return json(res,404,{error:'not_found'});const members=db.prepare(`SELECT u.id,u.username,u.name,u.avatar,cm.role,cm.banned FROM chat_members cm JOIN users u ON u.id=cm.user_id WHERE cm.chat_id=?`).all(req.params.id);json(res,200,{group:g,members})});

app.post('/api/channels',auth,(req,res)=>{const username=String(req.body.username||'').replace(/^@/,'').toUpperCase();if(!/^[A-Z0-9_]{3,24}$/.test(username))return json(res,400,{error:'bad_username'});if(db.prepare('SELECT 1 FROM channels WHERE lower(username)=lower(?)').get('@'+username))return json(res,409,{error:'username_taken'});const cid=id();db.prepare('INSERT INTO channels VALUES(?,?,?,?,?,?,?)').run(cid,'@'+username,String(req.body.name||'Канал').slice(0,80),String(req.body.description||'').slice(0,500),req.user.id,'',now());db.prepare('INSERT INTO channel_members VALUES(?,?,?)').run(cid,req.user.id,'owner');json(res,201,{channel:db.prepare('SELECT * FROM channels WHERE id=?').get(cid)})});
app.get('/api/channels',auth,(req,res)=>{const rows=db.prepare('SELECT * FROM channels ORDER BY created_at DESC LIMIT 50').all();json(res,200,{channels:rows})});
app.get('/api/channels/mine',auth,(req,res)=>{const rows=db.prepare(`SELECT c.*,cm.role FROM channel_members cm JOIN channels c ON c.id=cm.channel_id WHERE cm.user_id=? ORDER BY c.created_at DESC`).all(req.user.id);json(res,200,{channels:rows})});
app.post('/api/channels/:id/admin',auth,(req,res)=>{const owner=db.prepare(`SELECT 1 FROM channel_members WHERE channel_id=? AND user_id=? AND role='owner'`).get(req.params.id,req.user.id);if(!owner)return json(res,403,{error:'forbidden'});db.prepare(`UPDATE channel_members SET role='admin' WHERE channel_id=? AND user_id=?`).run(req.params.id,req.body.userId);json(res,200,{ok:true})});
app.delete('/api/channels/:id/admin/:userId',auth,(req,res)=>{const owner=db.prepare(`SELECT 1 FROM channel_members WHERE channel_id=? AND user_id=? AND role='owner'`).get(req.params.id,req.user.id);if(!owner)return json(res,403,{error:'forbidden'});db.prepare(`UPDATE channel_members SET role='subscriber' WHERE channel_id=? AND user_id=?`).run(req.params.id,req.params.userId);json(res,200,{ok:true})});
app.post('/api/channels/:id/subscribe',auth,(req,res)=>{db.prepare('INSERT OR IGNORE INTO channel_members VALUES(?,?,?)').run(req.params.id,req.user.id,'subscriber');json(res,200,{ok:true})});
app.post('/api/channels/:id/posts',auth,(req,res)=>{const c=db.prepare('SELECT * FROM channels WHERE id=?').get(req.params.id);const cm=db.prepare('SELECT role FROM channel_members WHERE channel_id=? AND user_id=?').get(req.params.id,req.user.id);if(!c||!cm||!['owner','admin'].includes(cm.role))return json(res,403,{error:'forbidden'});const pid=id();db.prepare('INSERT INTO channel_posts VALUES(?,?,?,?,?,?)').run(pid,c.id,req.user.id,String(req.body.content||''),String(req.body.media||''),now());json(res,201,{post:db.prepare('SELECT * FROM channel_posts WHERE id=?').get(pid)})});
app.get('/api/channels/:id/posts',auth,(req,res)=>json(res,200,{posts:db.prepare('SELECT * FROM channel_posts WHERE channel_id=? ORDER BY created_at DESC LIMIT 100').all(req.params.id)}));

app.post('/api/reports',auth,async(req,res)=>{const rid=id();const reason=String(req.body.reason||'Без описания').slice(0,2000);db.prepare('INSERT INTO reports VALUES(?,?,?,?,?,?,?)').run(rid,req.user.id,req.body.targetId||null,req.body.chatId||null,reason,now(),'open');let emailed=false;if(process.env.SMTP_HOST){try{const transporter=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:Number(process.env.SMTP_PORT||587)===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await transporter.sendMail({from:process.env.SMTP_FROM,to:process.env.REPORT_EMAIL||'endnrjdjdjrnr@gmail.com',subject:'Жалоба VYBINKA '+rid,text:`Reporter: ${req.user.username}\nTarget: ${req.body.targetId||''}\nChat: ${req.body.chatId||''}\nReason: ${reason}`});emailed=true}catch(e){console.error('SMTP:',e.message)}}json(res,201,{ok:true,reportId:rid,emailed})});

const MISTRAL_SYSTEM=`Ты Лили — официальный дружелюбный AI-помощник VYBINKA 10+. Ты знаешь сайт: регистрация, профиль, аватар, обложка, музыка, интересы, настроение, лента, лайки/не нравится, поиск по @username, чаты, фото/видео/голосовые, одноразовые фото, стикеры, группы, каналы, чат-рулетка, блокировки, жалобы и безопасность. Отвечай по-русски. Не выдавай себя за человека. Для пользователей младше 18 не поддерживай романтический/сексуальный контент и не проси адрес, школу, телефон, пароли, коды или другие чувствительные данные. Если пользователь расстроен — поддержи и предложи безопасные шаги. Будь краткой, доброй и конкретной.`;
async function mistral(messages){if(!process.env.MISTRAL_API_KEY)throw new Error('not_configured');const r=await fetch('https://api.mistral.ai/v1/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+process.env.MISTRAL_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.MISTRAL_MODEL||'mistral-small-latest',messages:[{role:'system',content:MISTRAL_SYSTEM},...messages.slice(-16)],temperature:.65,max_tokens:700})});const d=await r.json();if(!r.ok)throw new Error(d.message||'mistral_error');return d.choices?.[0]?.message?.content||'Попробуй ещё раз.'}
app.post('/api/lily',auth,async(req,res)=>{const messages=Array.isArray(req.body.messages)?req.body.messages.filter(x=>x&&['user','assistant'].includes(x.role)).slice(-16):[];if(!messages.length)return json(res,400,{error:'empty'});try{return json(res,200,{reply:await mistral(messages),mode:'mistral'})}catch(e){const q=String(messages[messages.length-1].content||'').toLowerCase();let reply='Я Лили 🪽. Сейчас Mistral недоступен, но я могу помочь с VYBINKA: спроси, как открыть чаты, рулетку, профиль, группы, каналы или настройки безопасности.';if(q.includes('рулет'))reply='Открой «Рулетка» в нижнем островке, выбери возраст и город собеседника и запусти подбор. 🪽';if(q.includes('жалоб'))reply='Открой профиль пользователя или меню чата → «Пожаловаться», укажи причину. Жалоба сохраняется на сервере и при настроенной почте отправляется модерации.';if(q.includes('стикер'))reply='В чате нажми кнопку стикеров. Набор VYBINKA загружается из серверных файлов, поэтому он одинаковый для всех.';return json(res,200,{reply,mode:'fallback'})}});

app.use((err,req,res,next)=>{console.error('HTTP:',err.stack||err);if(res.headersSent)return next(err);const code=err.code==='LIMIT_FILE_SIZE'?413:400;return json(res,code,{error:err.message||'request_failed'})});
app.get(/.*/,(req,res)=>res.sendFile(path.join(PUBLIC,'index.html')));
const server=http.createServer(app);const wss=new WebSocketServer({server});const sockets=new Map();
function broadcast(chatId,payload){const members=db.prepare('SELECT user_id FROM chat_members WHERE chat_id=? AND banned=0').all(chatId);for(const m of members){const set=sockets.get(m.user_id);if(set)for(const ws of set)if(ws.readyState===1)ws.send(JSON.stringify(payload))}}
wss.on('connection',(ws,req)=>{const u=new URL(req.url,'http://localhost');const token=u.searchParams.get('token');const s=token&&db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(hash(token));if(!s){ws.close();return}const uid=s.user_id;if(!sockets.has(uid))sockets.set(uid,new Set());sockets.get(uid).add(ws);ws.on('close',()=>{sockets.get(uid)?.delete(ws);if(!sockets.get(uid)?.size)sockets.delete(uid)})});
server.listen(PORT,()=>console.log(`VYBINKA ready: http://localhost:${PORT}`));
